
import type { KgEntity, KgGraph, KgRelation, LandParcelProfile } from './knowledgeGraphMock';

/** 地块86完整画像（大冶市还地桥镇示例） */
export const PARCEL_PROFILE_86: LandParcelProfile = {
  basic: {
    parcel_code: 'DY-HQ-GQ-00086',
    parcel_name: '郭桥村一组地块A',
    area_mu: 8.6,
    land_type: '水田',
    quality_grade: '高标准农田',
    centroid: '114.9821, 30.0912',
    status: '正常经营',
  },
  admin_division: {
    path: '湖北省/黄石市/大冶市/还地桥镇/郭桥村',
    admin_code: '420281103214',
  },
  current_crop: {
    crop_code: 'CROP-RICE-JZ534',
    crop_name: '晶两优534',
    season: '中稻',
    year: 2024,
    plant_date: '2024-05-18',
  },
  planting_history: [
    { year: 2024, crop_name: '晶两优534', season: '中稻', yield_kg_mu: 580 },
    { year: 2023, crop_name: '黄华占', season: '中稻', yield_kg_mu: 552 },
    { year: 2022, crop_name: '油菜', season: '冬油菜', yield_kg_mu: 210 },
  ],
  operator: {
    entity_code: 'ENT-COOP-001',
    entity_name: '还地桥绿丰种植专业合作社',
    entity_type: '合作社',
    mode: '流转经营',
    since: '2023-01-01',
  },
  ownership: [
    {
      right_type: '承包权',
      holder: '张某某',
      share_ratio: '100%',
      cert_no: 'DY-CB-2019-086',
    },
  ],
  transfer: [
    {
      contract_id: 'TC-2023-0088',
      from: '张某某',
      to: '还地桥绿丰种植专业合作社',
      type: '出租',
      end_date: '2028-12-31',
      price_yuan_mu: '450',
    },
  ],
  soil_fertility: {
    latest_test: {
      date: '2024-03-15',
      ph: '6.2',
      om: '2.8%',
      n: '1.2 g/kg',
      p: '18 mg/kg',
      k: '120 mg/kg',
    },
    fertility_grade: 'III级',
    suitable_crops: ['水稻', '油菜', '蔬菜'],
  },
  farm_activities: [
    { date: '2024-05-18', type: '机插秧', input: '晶两优534种子', service: '—' },
    { date: '2024-06-20', type: '施肥', input: '复合肥 40kg/亩', service: '—' },
    { date: '2024-10-08', type: '机收', input: '—', service: '联合收割机' },
  ],
  yield_and_revenue: {
    latest: {
      year: 2024,
      total_kg: 4988,
      sales_kg: 4800,
      avg_price: 2.8,
      revenue_yuan: 13440,
    },
  },
  supply_chain: {
    path_summary:
      '地块 → 2024中稻产量 → 销售 → 金穗米业加工 → 鄂东南物流园 → 白沙洲市场 → 武汉商超订单',
    nodes: ['金穗米业', '鄂东南粮食物流园', '白沙洲农副产品大市场'],
  },
  risk_alerts: [
    {
      type: '流转到期提醒',
      level: '中',
      message: '流转合同 TC-2023-0088 将于 2028-12-31 到期，请提前备案续签',
      alert_time: '2025-01-01',
    },
  ],
};

const PARCEL_PROFILE_12: LandParcelProfile = {
  basic: {
    parcel_code: 'DY-BA-HS-00012',
    parcel_name: '保安镇护山村地块B',
    area_mu: 12.3,
    land_type: '旱地',
    quality_grade: '一般耕地',
    centroid: '114.89, 30.12',
    status: '正常经营',
  },
  admin_division: { path: '湖北省/黄石市/大冶市/保安镇/护山村', admin_code: '420281102205' },
  current_crop: {
    crop_code: 'CROP-VEG-BJ-01',
    crop_name: '包菜',
    season: '秋冬茬',
    year: 2024,
    plant_date: '2024-09-05',
  },
  planting_history: [
    { year: 2024, crop_name: '包菜', season: '秋冬茬', yield_kg_mu: 3200 },
    { year: 2023, crop_name: '玉米', season: '夏玉米', yield_kg_mu: 450 },
  ],
  operator: {
    entity_code: 'ENT-COOP-002',
    entity_name: '保安镇春润蔬菜合作社',
    entity_type: '合作社',
    mode: '自营',
    since: '2020-03-01',
  },
  ownership: [{ right_type: '承包权', holder: '李某某', share_ratio: '100%', cert_no: 'DY-CB-2020-012' }],
  transfer: [],
  soil_fertility: {
    latest_test: { date: '2024-04-02', ph: '6.8', om: '1.9%', n: '0.9', p: '12', k: '95' },
    fertility_grade: 'IV级',
    suitable_crops: ['蔬菜', '甘薯'],
  },
  farm_activities: [
    { date: '2024-09-05', type: '移栽', input: '包菜苗', service: '—' },
    { date: '2024-10-10', type: '追肥', input: '有机肥', service: '—' },
  ],
  yield_and_revenue: {
    latest: { year: 2024, total_kg: 39360, sales_kg: 38000, avg_price: 1.2, revenue_yuan: 45600 },
  },
  supply_chain: {
    path_summary: '地块 → 包菜产量 → 直销黄石农贸市场',
    nodes: ['黄石农副产品批发市场'],
  },
  risk_alerts: [
    { type: '肥力偏低', level: '低', message: '有机质低于2%，建议增施有机肥', alert_time: '2024-04-05' },
  ],
};

const PARCEL_PROFILE_45: LandParcelProfile = {
  basic: {
    parcel_code: 'DY-CG-YT-00045',
    parcel_name: '陈贵镇洋塘村地块C',
    area_mu: 5.2,
    land_type: '菜地',
    quality_grade: '菜田',
    centroid: '114.95, 30.05',
    status: '正常经营',
  },
  admin_division: { path: '湖北省/黄石市/大冶市/陈贵镇/洋塘村', admin_code: '420281104108' },
  current_crop: {
    crop_code: 'CROP-OIL-YC-09',
    crop_name: '油菜',
    season: '冬油菜',
    year: 2024,
    plant_date: '2024-10-20',
  },
  planting_history: [{ year: 2024, crop_name: '油菜', season: '冬油菜', yield_kg_mu: 195 }],
  operator: {
    entity_code: 'ENT-FARMER-088',
    entity_name: '张某某',
    entity_type: '农户',
    mode: '自营',
    since: '2018-01-01',
  },
  ownership: [{ right_type: '承包权', holder: '张某某', share_ratio: '100%', cert_no: 'DY-CB-2018-045' }],
  transfer: [],
  soil_fertility: {
    latest_test: { date: '2024-03-28', ph: '6.5', om: '3.2%', n: '1.4', p: '22', k: '135' },
    fertility_grade: 'II级',
    suitable_crops: ['油菜', '水稻', '蔬菜'],
  },
  farm_activities: [{ date: '2024-10-20', type: '播种', input: '油菜籽', service: '—' }],
  yield_and_revenue: { latest: { year: 2023, total_kg: 1014, sales_kg: 980, avg_price: 3.5, revenue_yuan: 3430 } },
  supply_chain: { path_summary: '地块 → 油菜籽 → 本地压榨坊', nodes: ['陈贵镇榨油坊'] },
  risk_alerts: [],
};

export const AGRI_KNOWLEDGE_GRAPH: KgGraph = {
  entities: [
    {
      id: 'e_div_daye',
      name: '大冶市',
      type: 'admin_division',
      description: '湖北省黄石市县级市，农业地块产业链知识图谱示例区域。',
      properties: { 行政代码: '420281', 级别: '县级市', 所属: '黄石市' },
      aliases: ['大冶'],
    },
    {
      id: 'e_div_hq',
      name: '还地桥镇',
      type: 'admin_division',
      description: '大冶市西部乡镇，水稻主产区。',
      properties: { 行政代码: '420281103', 级别: '乡镇' },
      aliases: ['还地桥'],
    },
    {
      id: 'e_div_ba',
      name: '保安镇',
      type: 'admin_division',
      description: '大冶市南翼乡镇，蔬菜种植集中。',
      properties: { 行政代码: '420281102', 级别: '乡镇' },
    },
    {
      id: 'e_div_gq',
      name: '郭桥村',
      type: 'admin_division',
      description: '还地桥镇行政村。',
      properties: { 行政代码: '420281103214', 级别: '村' },
    },
    {
      id: 'e_parcel_86',
      name: '郭桥村一组地块A',
      type: 'land_parcel',
      description: '还地桥镇郭桥村核心示范地块，8.6亩水田，2024种植晶两优534中稻。',
      properties: { 地块编码: 'DY-HQ-GQ-00086', 面积: '8.6亩', 地类: '水田' },
      aliases: ['地块86', '郭桥村一组', 'DY-HQ-GQ-00086'],
      parcelProfile: PARCEL_PROFILE_86,
    },
    {
      id: 'e_parcel_12',
      name: '护山村地块B',
      type: 'land_parcel',
      description: '保安镇护山村旱地，12.3亩，2024种植包菜。',
      properties: { 地块编码: 'DY-BA-HS-00012', 面积: '12.3亩', 地类: '旱地' },
      aliases: ['地块12', '护山村地块'],
      parcelProfile: PARCEL_PROFILE_12,
    },
    {
      id: 'e_parcel_45',
      name: '洋塘村地块C',
      type: 'land_parcel',
      description: '陈贵镇洋塘村菜地，5.2亩，2024种植油菜。',
      properties: { 地块编码: 'DY-CG-YT-00045', 面积: '5.2亩', 地类: '菜地' },
      aliases: ['地块45', '洋塘村地块'],
      parcelProfile: PARCEL_PROFILE_45,
    },
    {
      id: 'e_crop_rice',
      name: '晶两优534',
      type: 'crop',
      description: '优质杂交中稻品种，适宜III级肥力水田。',
      properties: { 作物编码: 'CROP-RICE-JZ534', 类别: '粮食', 全生育期: '135天' },
      aliases: ['中稻', '水稻', '晶两优'],
    },
    {
      id: 'e_crop_huang',
      name: '黄华占',
      type: 'crop',
      description: '优质稻品种，2023年地块86种植品种。',
      properties: { 作物编码: 'CROP-RICE-HHZ', 类别: '粮食' },
    },
    {
      id: 'e_crop_oil',
      name: '油菜',
      type: 'crop',
      description: '冬油菜籽作物，肥力II–III级适宜。',
      properties: { 作物编码: 'CROP-OIL-YC-09', 类别: '油料' },
      aliases: ['冬油菜'],
    },
    {
      id: 'e_crop_veg',
      name: '包菜',
      type: 'crop',
      description: '秋冬茬蔬菜，适宜旱地种植。',
      properties: { 作物编码: 'CROP-VEG-BJ-01', 类别: '蔬菜' },
    },
    {
      id: 'e_farmer_zhang',
      name: '张某某',
      type: 'business_entity',
      description: '还地桥镇郭桥村农户，地块86承包权人。',
      properties: { 主体编码: 'ENT-FARMER-088', 类型: '农户', 村组: '郭桥村一组' },
      aliases: ['张姓农户'],
    },
    {
      id: 'e_coop_lvfeng',
      name: '还地桥绿丰合作社',
      type: 'business_entity',
      description: '还地桥镇种植专业合作社，经营地块86。',
      properties: { 主体编码: 'ENT-COOP-001', 类型: '合作社', 成员数: '32人' },
      aliases: ['绿丰合作社', '绿丰'],
    },
    {
      id: 'e_coop_ba',
      name: '保安镇春润合作社',
      type: 'business_entity',
      description: '保安镇蔬菜种植合作社。',
      properties: { 主体编码: 'ENT-COOP-002', 类型: '合作社' },
      aliases: ['春润合作社'],
    },
    {
      id: 'e_ent_jinsui',
      name: '金穗米业',
      type: 'processor',
      description: '大冶市稻谷加工企业，承接地块86稻谷收购加工。',
      properties: { 企业编码: 'ENT-ENT-003', 许可: '粮食加工SC', 产能: '120吨/日' },
      aliases: ['金穗米业', '大冶市金穗米业有限公司'],
    },
    {
      id: 'e_pr_2024_86',
      name: '2024中稻-地块86',
      type: 'planting_record',
      description: '2024年中稻季种植记录，品种晶两优534。',
      properties: { 记录编号: 'PR-2024-DY-0001', 年份: '2024', 季别: '中稻', 亩产: '580kg' },
    },
    {
      id: 'e_pr_2023_86',
      name: '2023中稻-地块86',
      type: 'planting_record',
      description: '2023年中稻季种植记录，品种黄华占。',
      properties: { 记录编号: 'PR-2023-DY-0008', 年份: '2023', 亩产: '552kg' },
    },
    {
      id: 'e_pr_2022_86',
      name: '2022油菜-地块86',
      type: 'planting_record',
      description: '2022年冬油菜种植记录。',
      properties: { 记录编号: 'PR-2022-DY-0015', 年份: '2022', 亩产: '210kg' },
    },
    {
      id: 'e_transfer_88',
      name: '流转合同TC-2023-0088',
      type: 'transfer_contract',
      description: '张某某向绿丰合作社出租地块86，8.6亩，450元/亩/年。',
      properties: { 合同编号: 'TC-2023-0088', 期限: '2023-2028', 状态: '履行中' },
    },
    {
      id: 'e_soil_86',
      name: '土壤检测2024-86',
      type: 'soil_test',
      description: '2024年3月还地桥农技站对地块86土壤采样检测。',
      properties: { 检测编号: 'ST-2024-086', 检测日期: '2024-03-15', 检测机构: '还地桥农技站' },
    },
    {
      id: 'e_fert_86',
      name: '肥力III级-86',
      type: 'fertility_grade',
      description: '地块86土壤肥力综合评价III级，宜稻、油菜。',
      properties: { 等级: 'III级', 评分: '78', 评价日期: '2024-03-20' },
    },
    {
      id: 'e_act_plant_86',
      name: '机插秧2024-86',
      type: 'farm_activity',
      description: '2024年5月18日机插秧农事活动。',
      properties: { 活动日期: '2024-05-18', 类型: '机插秧' },
    },
    {
      id: 'e_act_fert_86',
      name: '施肥2024-86',
      type: 'farm_activity',
      description: '2024年6月20日追肥，复合肥40kg/亩。',
      properties: { 活动日期: '2024-06-20', 类型: '施肥' },
    },
    {
      id: 'e_act_harvest_86',
      name: '机收2024-86',
      type: 'farm_activity',
      description: '2024年10月8日联合收割机收获。',
      properties: { 活动日期: '2024-10-08', 类型: '机收' },
    },
    {
      id: 'e_input_seed',
      name: '晶两优534种子',
      type: 'input_product',
      description: '2024中稻用种，批次L24-0501。',
      properties: { 投入品编码: 'IN-SEED-JZ534', 用量: '2.5kg/亩' },
    },
    {
      id: 'e_input_compost',
      name: '复合肥',
      type: 'input_product',
      description: '氮磷钾复合肥，农事施肥使用。',
      properties: { 投入品编码: 'IN-FERT-NPK', 用量: '40kg/亩' },
    },
    {
      id: 'e_machinery',
      name: '联合收割机服务',
      type: 'machinery_service',
      description: '还地桥镇农机合作社提供机收服务。',
      properties: { 服务编号: 'MS-2024-086', 费用: '80元/亩' },
    },
    {
      id: 'e_yield_86',
      name: '2024产量-地块86',
      type: 'yield_record',
      description: '2024中稻收获产量4988kg。',
      properties: { 产量编号: 'YR-2024-00086', 总产量: '4988kg', 等级: '一等' },
    },
    {
      id: 'e_sales_86',
      name: '2024销售-地块86',
      type: 'sales_record',
      description: '4800kg稻谷销售给绿丰合作社统一对接加工。',
      properties: { 销售编号: 'SR-2024-0086', 数量: '4800kg', 单价: '2.8元/kg' },
    },
    {
      id: 'e_warehouse',
      name: '鄂东南粮食物流园',
      type: 'warehouse',
      description: '黄石市粮食仓储物流节点，金穗米业合作库点。',
      properties: { 库点编码: 'WH-ES-001', 仓容: '5000吨', 类型: '常温仓储' },
      aliases: ['鄂东南物流园'],
    },
    {
      id: 'e_market',
      name: '白沙洲市场',
      type: 'market',
      description: '武汉白沙洲农副产品大市场，稻米批发集散地。',
      properties: { 市场编码: 'MK-BSZ-001', 城市: '武汉市洪山区' },
      aliases: ['白沙洲农副产品大市场'],
    },
    {
      id: 'e_order',
      name: '订单WH-1024',
      type: 'order',
      description: '武汉某商超精米采购订单，合同20吨。',
      properties: { 订单编号: 'ORD-2024-WH-1024', 数量: '20吨', 状态: '履约中' },
    },
    {
      id: 'e_risk_86',
      name: '流转到期提醒',
      type: 'risk_alert',
      description: '地块86流转合同2028年底到期预警。',
      properties: { 预警级别: '中', 预警时间: '2025-01-01' },
    },
  ],
  relations: [
    { id: 'r01', sourceId: 'e_parcel_86', targetId: 'e_div_gq', label: '属于' },
    { id: 'r02', sourceId: 'e_div_gq', targetId: 'e_div_hq', label: '属于' },
    { id: 'r03', sourceId: 'e_div_hq', targetId: 'e_div_daye', label: '属于' },
    { id: 'r04', sourceId: 'e_parcel_12', targetId: 'e_div_ba', label: '属于' },
    { id: 'r05', sourceId: 'e_div_ba', targetId: 'e_div_daye', label: '属于' },
    { id: 'r06', sourceId: 'e_parcel_45', targetId: 'e_div_daye', label: '属于' },
    { id: 'r07', sourceId: 'e_parcel_86', targetId: 'e_crop_rice', label: '当前种植' },
    { id: 'r08', sourceId: 'e_parcel_12', targetId: 'e_crop_veg', label: '当前种植' },
    { id: 'r09', sourceId: 'e_parcel_45', targetId: 'e_crop_oil', label: '当前种植' },
    { id: 'r10', sourceId: 'e_parcel_86', targetId: 'e_pr_2024_86', label: '种植记录' },
    { id: 'r11', sourceId: 'e_parcel_86', targetId: 'e_pr_2023_86', label: '种植记录' },
    { id: 'r12', sourceId: 'e_parcel_86', targetId: 'e_pr_2022_86', label: '种植记录' },
    { id: 'r13', sourceId: 'e_pr_2024_86', targetId: 'e_crop_rice', label: '种植作物' },
    { id: 'r14', sourceId: 'e_pr_2023_86', targetId: 'e_crop_huang', label: '种植作物' },
    { id: 'r15', sourceId: 'e_pr_2022_86', targetId: 'e_crop_oil', label: '种植作物' },
    { id: 'r16', sourceId: 'e_parcel_86', targetId: 'e_coop_lvfeng', label: '经营主体' },
    { id: 'r17', sourceId: 'e_parcel_12', targetId: 'e_coop_ba', label: '经营主体' },
    { id: 'r18', sourceId: 'e_parcel_45', targetId: 'e_farmer_zhang', label: '经营主体' },
    { id: 'r19', sourceId: 'e_parcel_86', targetId: 'e_farmer_zhang', label: '承包权人' },
    { id: 'r20', sourceId: 'e_parcel_86', targetId: 'e_transfer_88', label: '流转' },
    { id: 'r21', sourceId: 'e_transfer_88', targetId: 'e_coop_lvfeng', label: '承租方' },
    { id: 'r22', sourceId: 'e_transfer_88', targetId: 'e_farmer_zhang', label: '出租方' },
    { id: 'r23', sourceId: 'e_parcel_86', targetId: 'e_soil_86', label: '土壤检测' },
    { id: 'r24', sourceId: 'e_parcel_86', targetId: 'e_fert_86', label: '肥力等级' },
    { id: 'r25', sourceId: 'e_fert_86', targetId: 'e_crop_rice', label: '适宜' },
    { id: 'r26', sourceId: 'e_fert_86', targetId: 'e_crop_oil', label: '适宜' },
    { id: 'r27', sourceId: 'e_coop_lvfeng', targetId: 'e_act_plant_86', label: '开展农事' },
    { id: 'r28', sourceId: 'e_act_plant_86', targetId: 'e_parcel_86', label: '作用于' },
    { id: 'r29', sourceId: 'e_coop_lvfeng', targetId: 'e_act_fert_86', label: '开展农事' },
    { id: 'r30', sourceId: 'e_act_fert_86', targetId: 'e_parcel_86', label: '作用于' },
    { id: 'r31', sourceId: 'e_coop_lvfeng', targetId: 'e_act_harvest_86', label: '开展农事' },
    { id: 'r32', sourceId: 'e_act_harvest_86', targetId: 'e_parcel_86', label: '作用于' },
    { id: 'r33', sourceId: 'e_act_plant_86', targetId: 'e_input_seed', label: '使用投入品' },
    { id: 'r34', sourceId: 'e_act_fert_86', targetId: 'e_input_compost', label: '使用投入品' },
    { id: 'r35', sourceId: 'e_act_harvest_86', targetId: 'e_machinery', label: '农机服务' },
    { id: 'r36', sourceId: 'e_parcel_86', targetId: 'e_yield_86', label: '产出' },
    { id: 'r37', sourceId: 'e_yield_86', targetId: 'e_crop_rice', label: '作物产量' },
    { id: 'r38', sourceId: 'e_yield_86', targetId: 'e_sales_86', label: '销售' },
    { id: 'r39', sourceId: 'e_sales_86', targetId: 'e_ent_jinsui', label: '加工' },
    { id: 'r40', sourceId: 'e_ent_jinsui', targetId: 'e_warehouse', label: '入库' },
    { id: 'r41', sourceId: 'e_warehouse', targetId: 'e_market', label: '配送' },
    { id: 'r42', sourceId: 'e_market', targetId: 'e_order', label: '履约订单' },
    { id: 'r43', sourceId: 'e_parcel_86', targetId: 'e_risk_86', label: '风险预警' },
    { id: 'r44', sourceId: 'e_coop_lvfeng', targetId: 'e_div_hq', label: '位于' },
    { id: 'r45', sourceId: 'e_ent_jinsui', targetId: 'e_div_daye', label: '位于' },
  ],
};

export const NL_QUERY_EXAMPLES_AGRI = [
  '郭桥村一组地块A到白沙洲市场有哪些关联路径？',
  '查询还地桥绿丰合作社周边2跳的实体关系',
  '晶两优534与金穗米业有什么关系',
  '地块86的土壤肥力适宜种植什么作物',
];
